db:
  image: "mysql:5.6"
  volumes:
    - ~/.docker-volumes/anotae/db/:/var/lib/mysql/data/
  ports: 
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: anotae_production
    MYSQL_USER: root
    MYSQL_PASSWORD: root
  expose:
    - '3306'

app:
  build: .
  command: bundle exec puma -p 9001 -e production
  environment:
    - RAILS_ENV=production
  volumes:
    - .:/usr/src/app
  expose:
    - '9001'
  links:
    - db

web:
  image: infoslack/nginx-puma
  volumes_from:
    - app
  ports:
    - '80:80'
  links:
    - app
